Task3
scosme20/Desafio-instituto-taqtile pull request #16
Opened 2024-06-25 02:37 UTC by scosme20

2024-06-27 20:52 UTC, racsandoval reviewed
Como esse PR está apontando pra develop, ele está com alteração dos PRs anteriores, tornando bem difícil de fazer o code review

2024-06-27 21:53 UTC, scosme20 commented
vou consertar isso

2024-06-28 17:11 UTC, SamuelSsc reviewed
Do que se trata esse pr? quais funcionalidades foram implementadas nele?

2024-06-28 17:13 UTC, SamuelSsc requested changes
O ponto que o Rafael comentou anteriormente sobre o pr estar apontando para develop e mostrando implementações de outras branches ainda precisa ser ajustado, é preciso que aqui o pr compare com a branch da qual ele partiu como discutimos nos plantões de duvidas, para que mostre apenas as alterações implementadas aqui.

2024-06-28 17:18 UTC, SamuelSsc commented on desafio-taqtile/src/Pages/LoginPage.tsx
> +  const [login] = useMutation(LOGIN_MUTATION);
o seu hook useMutation tem um estado de login gerenciado internamente, você não precisa criar um state para isso, pode pegar o daqui

2024-06-28 17:20 UTC, SamuelSsc commented on desafio-taqtile/src/Pages/LoginPage.tsx
> +      } catch (error: any) {
Seu hook do apolo useMutation tbm tem uma forma melhor de lidar com isso, através de onError e onSuccess

2024-06-28 21:26 UTC, closed without merging